---
- name: Install cert package dependencies.
  apt:
    name:
      - ssl-cert
    state: present

- name: Generate snakeoil certs.
  ansible.builtin.command: make-ssl-cert generate-default-snakeoil
  changed_when: false

- name: Add proxy user to ssl-cert group.
  ansible.builtin.user:
    name: www-data
    groups: ssl-cert
    append: true
