---
- name: Make snakeoil certs
  ansible.builtin.command: make-ssl-cert generate-default-snakeoil
  changed_when: false

- name: Add webserver user to ssl-cert group
  ansible.builtin.user:
    name: www-data
    groups: ssl-cert
    append: true
