---
- name: Template jellyfin main config
  ansible.builtin.template:
    src: templates/etc/default/jellyfin.j2
    dest: /etc/default/jellyfin
    owner: root
    group: root
    mode: "{{ jellyfin_permission_etc_file }}"
  notify:
    - restart_jellyfin

- name: Configure systemd service override
  ansible.builtin.template:
    src: templates/etc/systemd/system/jellyfin.service.d/ansible_managed.conf.j2
    dest: /etc/systemd/system/jellyfin.service.d/ansible_managed.conf
    owner: root
    group: root
    mode: "{{ jellyfin_permission_etc_file }}"
  notify:
    - restart_jellyfin
    - systemd_daemon_reload
