---
- name: Configure Jellyfin
  ansible.builtin.template:
    src: templates/config.jinja
    dest: /etc/default/jellyfin
    force: true
    owner: "{{ jellyfin_unix_user }}"
    group: "{{ jellyfin_unix_group }}"
    mode: "0744"
  notify: Restart Jellyfin
