---
- name: Include vanilla var overrides if in vanilla mode
  include_vars:
    file: "vars/vanilla_mode.yml"

- name: Stop and disable any non vanilla systemd services
  meta: noop
  changed_when: true
  notify:
    - stop_disable_non_vanilla
