---
- name: Restart jellyfin
  ansible.builtin.systemd:
    name: jellyfin.service
    state: restarted
  listen: restart_jellyfin
  when: not (jellyfin_skip_restart | bool)

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban.service
    state: restarted
  listen: Restart fail2ban

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
  listen: reload_nginx

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: systemd_daemon_reload
